export const FETCH_SPACE_DATA = 'FETCH_SPACE_DATA';
export const FETCH_SPACE_PAYLOAD = 'FETCH_SPACE_PAYLOAD';
export const FILTER_TEXT = "FILTER_TEXT";
export const LOAD_NEW_PAGE = "LOAD_NEW_PAGE";
export const LOAD_EXACT_PAGE = "LOAD_EXACT_PAGE";
export const FILTER_BY_VALUE = "FILTER_BY_VALUE";
export const FILTER_BY_PAYLOAD_VALUE = "FILTER_BY_PAYLOAD_VALUE";